<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>false</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VsDebugMcp</RootNamespace>
    <AssemblyName>VsDebugMcp</AssemblyName>
    <Version>0.5.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="envdte" Version="17.14.40260" />
    <PackageReference Include="envdte80" Version="17.14.40260" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Content\debug_instructions.md" />
    <EmbeddedResource Include="Resources\Content\troubleshooting_csharp.md" />
    <EmbeddedResource Include="Resources\Content\troubleshooting_cpp.md" />
    <EmbeddedResource Include="Resources\Content\troubleshooting_fsharp.md" />
    <EmbeddedResource Include="Resources\Content\troubleshooting_vb.md" />
  </ItemGroup>

</Project>
